FORMAT: 1A
HOST: https://license.colorfront.com

# License API

License API allows you to request a license from the Colorfront license server. 

## License Collection [/license.php]

### Request a license [GET]

+ Request (application/json)

    + Header
    
            Authorization: Basic Y29sb3Jmcm9udDpjMGwwcmZyMG50
            
    + Body
    
            {
            "hostid": "123456-123456-123456",
            "company": "COLORFRONT"
            }

+ Response 200 (application/json)

    + Body

            {
            "timestamp":"2016-09-10T01:05:21-07:00",
            "status":200,
            "hostid":"123456-123456-123458",
            "company":"COLORFRONT",
            "license":"123456-123456-123458-160910-160910-C40000-000000-COLORFRONT-160910-8657X-3UC2D-ARO0A-UH7NB-T6PMA-30D7A-KATJB-AGRB5-NRKSE-J5O46-C1M81-52I68-KP411-LCJ6E-8GEG2-OJP6F-18FA6-NC8DE-77KC2-8C1CD-PKNK9-MIF93-Q0OOA-4VGJA-PCC15-HQRGF-B198E-0G8E3"
            }